[project]
name = "spending-import"
version = "0.1.0"
description = ""
dependencies = [
    "pynab",
]
package-dir = {"spendingimport" = "src"}
requires-python = ">=3.14"
authors = [
    {name = "Isaac Wagner", email = "isaac.wagner@gmail.com"}]

[dependency-groups]
dev = [
    "boto3>=1.42.12",
    "botocore>=1.42.12",
    "pytest>=9.0.2",
]

[tool.uv.sources]
pynab = { git = "https://github.com/idwagner/pynab" }

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"] # Check uv documentation for the latest version requirement
build-backend = "uv_build"
